### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'text'

### ISSUE THREAD

**Issue by pbtsrc** [SiddharthSaxena/PyCurrency-Converter#1]
```
>>> import PyCurrency_Converter
>>> PyCurrency_Converter.convert(1, 'USD', 'INR')
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/Work/venve2p/lib/python3.5/site-packages/PyCurrency_Converter/PyCurrency.py", line 48, in convert
    return PyCurrency.convert(amount, _from, _to)
  File "/home/Work/venve2p/lib/python3.5/site-packages/PyCurrency_Converter/PyCurrency.py", line 33, in convert
    parsed = BeautifulSoup(html, 'lxml').body.find('span', attrs={'class': 'bld'}).text
AttributeError: 'NoneType' object has no attribute 'text'
>>> 
```

python 3.5.3
beautifulsoup4-4.6.0
lxml-4.0.0

**Comment by SiddharthSaxena** [comment]
Apparently, Google changed the URL from https://www.google.com/finance/converter to https://finance.google.com/finance/converter. This error should be fixed now

**Comment by hadeelfouad** [comment]
Still getting the same error.
```
File "F:\Work\travel\travel_env\lib\site-packages\PyCurrency_Converter\P
Currency.py", line 48, in convert
    return PyCurrency.convert(amount, _from, _to)
  File "F:\Work\travista\travista3_env\lib\site-packages\PyCurrency_Converter\P
Currency.py", line 33, in convert
    parsed = BeautifulSoup(html, 'lxml').body.find('span', attrs={'class': 'bld}).text
AttributeError: 'NoneType' object has no attribute 'text'
```

**Comment by SiddharthSaxena** [comment]
Recent changes in Google Finance's API model has resulted in breaking the utility of this package. I'm looking to fix it as soon as I can. It should not take much time.
