### ISSUE TITLE
HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by devleifr** [SiddharthSaxena/PyCurrency-Converter#2]
``
import PyCurrency_Converter as conv
``
``
conv.convert(1, 'USD', 'INR')
``
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/glebdom4/.local/lib/python3.6/site-packages/PyCurrency_Converter/PyCurrency.py", line 48, in convert
    return PyCurrency.convert(amount, _from, _to)
  File "/home/glebdom4/.local/lib/python3.6/site-packages/PyCurrency_Converter/PyCurrency.py", line 31, in convert
    response = urllib2.urlopen(url)
  File "/usr/lib64/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib64/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python3.6/urllib/request.py", line 564, in error
    result = self._call_chain(*args)
  File "/usr/lib64/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib64/python3.6/urllib/request.py", line 756, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib64/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib64/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python3.6/urllib/request.py", line 564, in error
    result = self._call_chain(*args)
  File "/usr/lib64/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib64/python3.6/urllib/request.py", line 756, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib64/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib64/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib64/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib64/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

**Comment by SiddharthSaxena** [comment]
Recent changes in Google Finance's API model has resulted in breaking the utility of this package. I'm looking to fix it as soon as I can. It should not take much time.

**Comment by macdonjo** [comment]
>>> import PyCurrency_Converter
>>> PyCurrency_Converter.convert(1, 'USD', 'GBP')
Traceback (most recent call last):
  File "<pyshell#8>", line 1, in <module>
    PyCurrency_Converter.convert(1, 'USD', 'GBP')
  File "D:\Users\macdo\AppData\Local\Programs\Python\Python39\lib\site-packages\PyCurrency_Converter\PyCurrency.py", line 48, in convert
    return PyCurrency.convert(amount, _from, _to)
  File "D:\Users\macdo\AppData\Local\Programs\Python\Python39\lib\site-packages\PyCurrency_Converter\PyCurrency.py", line 31, in convert
    response = urllib2.urlopen(url)
  File "D:\Users\macdo\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "D:\Users\macdo\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 523, in open
    response = meth(req, response)
  File "D:\Users\macdo\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 632, in http_response
    response = self.parent.error(
  File "D:\Users\macdo\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 561, in error
    return self._call_chain(*args)
  File "D:\Users\macdo\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)
  File "D:\Users\macdo\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

**Comment by st-rom** [comment]
Has this error ever been fixed or is this library deprecated?
